### ISSUE TITLE
Stripe interface not showing

### ISSUE THREAD

**Issue by avetise** [AgentBurgundy/fire-saas#4]
http://localhost:3000/api/stripe/portal 404 (Not Found)

StripeProductData empty:
No products showing on 
export default function SubscriptionCard({
  product,
}: {
  product: StripeProductData;
}) {

Both "Upgrade" buttons not showing stripe interface.

**Comment by AgentBurgundy** [comment]
I'll take a look, there's some things I've been meaning to update in this project but haven't had much time

**Comment by AgentBurgundy** [comment]
This should be resolved as of the latest version. Closing for now, but reach back out if there are more issues!

**Comment by avetise** [comment]
Cannot find module '@/lib/types/StripeProductData' or its corresponding type declarations.ts(2307)

**Comment by avetise** [comment]
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'map')

Source
src\components\subscription\SubscriptionCard.tsx (43:29) @ map
